### ISSUE TITLE
Implement world blacklist/whitelist & WG region blacklist/whitelist

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [Mrcomputer1/SmileyPlayerTrader#76]
Currently there is only disabled_worlds option

i think there should be

```yml
allowed_worlds:
    mode: BLACKLIST
    list:
    - world
    - world_nether
    - world_the_end
allowed_regions: # works only if WG is installed
    mode: WHITELIST
    list:
    - spawn # there probably how this could be done per world but i never saw that neither i used plugin which does that, maybe we can list something like "<worldname>:<regioname>" for example "world:spawn" where "world" is world name and "spawn" is WG region name
```

I think this will be very useful because we can then decide where RIGHT-CLICK on player will be used and where not, because if it's somewhere PvP region inside of overworld, and then there is some feature like in 1.7 there was blocking with right click, maybe player will still use it depending on server setup, and it will try to right click on player with sword which will open trade menu... this feature just makes plugin more flexible! i hope it's ok

Also i think there should also be custom SmileyPlayerTrader WG flag which we can use also, then we don't really need to use the settings in config but just to ensure that our worlds are enabled and that we have mode for allowed_regions to BLACKLIST and empty list, then we just set __global__ region flag for `smiley trading` to DENY and then for example we create trading warp, we define it as WG region "trading_museum" and then we give it higher priority than __global__ region + we also apply flag for `smiley trading` to ALLOW!

Hope i did not complicate everything
